#!/bin/bash
./compile

# If out.fst does not exist, do not generate an error message. 
rm -f -- out.fst

stty -icanon -echo

osStr=$(uname)
cpuStr=$(uname -m)
if [[ "$osStr" == 'Darwin' ]] && [[ "$cpuStr" = 'arm64' ]] ; then
    echo  Loading Hana1 on Mac OS will halt on errors, no tracing. 
    ./Hana1.macos -halt      

elif [[ "$osStr" == 'Linux' ]] && [[ "$cpuStr" = 'x86' ]] ; then
    echo  Loading Hana1 on Linux will halt on errors, no tracing.     
    ./Hana1.linux -halt     
else
  echo "Only Mac OS on Apple hardware, and Linux on x86 are supported"
fi

stty sane

